import type { ComposerGraph } from './composer-graph.js'

/**
 * @description Generates a TypeScript module string that embeds the graph and returns `createOS()` for you to register agents against.
 * @param graph Validated composer graph.
 */
export function generateComposeTsModule(graph: ComposerGraph): string {
  const json = JSON.stringify(graph, null, 2)
  const agentIds = [...new Set(graph.nodes.map((n) => n.data.agentId))]

  return `/**
 * Auto-generated by OpenOS Composer (Phase 2).
 * Replace TODO sections with real agent imports, then call \`createComposedOs()\`.
 */
import { createOS } from '@open-os/sdk'

export const COMPOSER_GRAPH = ${json} as const

export function createComposedOs() {
  const os = createOS()
  // TODO: import agents and call os.use(...) for: ${agentIds.join(', ')}
  // Example:
  // import agentA from './agents/agent-a.js'
  // os.use(agentA)
  return os
}
`
}
